[package]
authors = ["Liang Yongrui <leungyongrui@gmail.com>"]
edition = "2021"
exclude = ["dist", "build", "assets", "credits"]
name = "dodge-the-creeps-bevy"
publish = false
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
dev = ["bevy/dynamic"]

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
  "bevy_asset",
  "bevy_winit",
  "render",
  "png",
  "x11"
] }
bevy_asset_loader = { version = "0.12" }
bevy_kira_audio = { version = "0.12", features = ["wav"] }
bevy_rapier2d = { version = "0.16" }
rand = { version = "0.8" }
benimator = { version = "4.0.0-rc.1" }

# keep the following in sync with Bevy's dependencies
image = { version = "0.24", default-features = false }
winit = { version = "0.26.0", default-features = false }

[build-dependencies]
embed-resource = "1.4"
